Map<String, dynamic> amenitiesOptions = {
  "minStorageUnits": "Min Storage Units",
  "loadingDocks": "Loading Docks",
  "climateControl": "Climate Control",
  "onSiteStaff": "On Site Staff",
  "packagingSupplies": "Packaging Supplies",
  "rackingSystems": "Racking Systems",
  "securitySystems": "Security Systems",
  "fireSuppressionSystems": "Fire Suppression Systems",
  "access24_7": "Access 24/7",
  "forkliftAvailability": "Forklift Availability",
  "wifiAccess": "WiFi Access",
  "backupGenerators": "Backup Generators",
  "cctvSurveillance": "CCTV Surveillance",
  "accessControlSystems": "Access Control Systems",
  "palletJacks": "Pallet Jacks",
  "sprinklerSystems": "Sprinkler Systems",
  "breakRooms": "Break Rooms",
  "conferenceRooms": "Conference Rooms",
  "restrooms": "Restrooms",
  "truckParking": "Truck Parking",
  "wasteDisposal": "Waste Disposal",
  "elevatorAccess": "Elevator Access",
  "highCeilings": "High Ceilings",
  "ventilationSystems": "Ventilation Systems",
  "energyEfficientLighting": "Energy Efficient Lighting"
};
