Map<String, String> spaceTypes = {
  'warehouseSpace': 'Warehouse Space',
  'privateOffice': 'Private Office',
  'eventSpace': 'Event Space',
  'broadcastStudios': 'Broadcast Studios',
  'pickleBall': 'Pickle Ball',
  'crossDocks': 'Cross Docks',
  'meetingRoom': 'Meeting Room',
  'coworkingSpace': 'Coworking Space',
  'conferenceHall': 'Conference Hall',
  'storageUnits': 'Storage Units',
  'virtualOffice': 'Virtual Office',
  'industrialSpace': 'Industrial Space',
  'retailSpace': 'Retail Space',
  'sharedOffice': 'Shared Office',
  'fitnessCenter': 'Fitness Center',
  'laboratorySpace': 'Laboratory Space',
  'creativeStudio': 'Creative Studio',
  'trainingRoom': 'Training Room',
  'researchFacility': 'Research Facility'
};
