import 'package:flutter/material.dart';

final Map<String, IconData> amenityIcons = {
  'minStorageUnits': Icons.storage,
  'loadingDocks': Icons.local_shipping,
  'climateControl': Icons.ac_unit,
  'onSiteStaff': Icons.person,
  'packagingSupplies': Icons.all_inbox,
  'rackingSystems': Icons.view_column,
  'securitySystems': Icons.security,
  'fireSuppressionSystems': Icons.local_fire_department,
  'access24_7': Icons.access_time,
  'forkliftAvailability': Icons.agriculture,
  'wifiAccess': Icons.wifi,
  'backupGenerators': Icons.power,
  'cctvSurveillance': Icons.videocam,
  'accessControlSystems': Icons.lock,
  'palletJacks': Icons.handyman,
  'sprinklerSystems': Icons.water_damage,
  'breakRooms': Icons.free_breakfast,
  'conferenceRooms': Icons.meeting_room,
  'restrooms': Icons.wc,
  'truckParking': Icons.local_parking,
  'wasteDisposal': Icons.delete,
  'elevatorAccess': Icons.elevator,
  'highCeilings': Icons.roofing,
  'ventilationSystems': Icons.air,
  'energyEfficientLighting': Icons.lightbulb_outline,
};
