name: cubework_app_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets: 
  - lib/assets/.env
  - lib/assets/locations.json
